services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - env/dev.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/dev.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
