services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    env_file:
      - env/test.env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - env/test.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
