FROM python:3.10-slim

WORKDIR /app

COPY requirements/requirements.test.txt .
RUN pip install --no-cache-dir -r requirements.test.txt

COPY . .

ENV PYTHONPATH=/app
ENV TESTING=True

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
